graph LR
    subgraph Networks
        SEP[Ethereum Sepolia<br/>Chain ID: 11155111]
        LAS[Lasna Reactive<br/>Chain ID: 5318007]
        BAS[Base Sepolia<br/>Chain ID: 84532]
    end
    
    subgraph Explorers
        SEP --> SE[sepolia.etherscan.io]
        LAS --> LE[lasna-explorer.rnk.dev]
        BAS --> BE[sepolia.basescan.org]
    end
