graph LR
    subgraph "Supported Assets"
        WETH["WETH<br/>Aave V3 - 20%<br/>ETH/USD Bridge"]
        LINK["LINK<br/>Aave V3 - 20%<br/>LINK/USD Bridge"]
        AAVE["AAVE<br/>Aave V3 - 20%<br/>CoinGecko"]
        EURS["EURS<br/>Aave V3 - 10%<br/>EUR/USD Bridge"]
        WBTC["WBTC<br/>Aave V3 - 15%<br/>BTC/USD Bridge"]
    end
    
    style WETH fill:#627eea
    style LINK fill:#2a5ada
    style AAVE fill:#b6509e
    style EURS fill:#2775ca
    style WBTC fill:#f7931a
